# ################################################################################
#  Copyright (c) 2026  Claudio André <portfolio-2026br at claudioandre.slmail.me>
#              ___                _      ___       _
#             (  _`\             ( )_  /'___)     (_ )  _
#             | |_) )  _    _ __ | ,_)| (__   _    | | (_)   _
#             | ,__/'/'_`\ ( '__)| |  | ,__)/'_`\  | | | | /'_`\
#             | |   ( (_) )| |   | |_ | |  ( (_) ) | | | |( (_) )
#             (_)   `\___/'(_)   `\__)(_)  `\___/'(___)(_)`\___/'
#
# This program comes with ABSOLUTELY NO WARRANTY; express or implied.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, as expressed in version 2, seen at
# https://www.gnu.org/licenses/gpl-2.0.html
# ################################################################################
# GitHub Action to run some linters
# More info at https://github.com/portfolio-2026br/security

---
name: "Linter de Código"

"on":
  pull_request:
    branches: ["main"]
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: linter

    permissions:
      statuses: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            api0.prismacloud.io:443
            check.trivy.dev:443
            github.com:443
            mirror.gcr.io:443
            pypi.org:443

      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Linter
        uses: super-linter/super-linter@ffde3b2b33b745cb612d787f669ef9442b1339a6 # v8.1.0
        env:
          ENABLE_COMMITLINT_STRICT_MODE: true
          ENFORCE_COMMITLINT_CONFIGURATION_CHECK: true
          FIX_MARKDOWN_PRETTIER: true
          FIX_YAML_PRETTIER: true
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check
        run: |
          echo "You should format source code properly!"
          echo "**********************************************************************"
          git diff
          echo "**********************************************************************"
          git diff --quiet
